version: '3'

services:
  staxter_service:
    image: staxter_image:1
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        max_attempts: 10
        delay: 2s	  
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "80:8080"