version: '3'

services:
  staxter_service:
    image: staxter_image:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "80:8081"